insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(1, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(2, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(3, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(4, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(5, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(6, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(7, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(8, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(9, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(10, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(11, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(12, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');
insert into log(ID, DATA, REQUEST, IP,STATUS,USER_AGENT) values(13, CURRENT_TIMESTAMP,'HTTP', '192.168.0.1','OK','USER DA GRUTA');




